### ISSUE TITLE
Export Window Links Do Not Work

### ISSUE THREAD

**Issue by Samuel6710** [Schwork-Corruption/corruptovania#14]
The links to Wii Backup Manager and Wimms Iso Tools do not open their respective sites. 

![image](https://github.com/user-attachments/assets/9666fda0-6903-4048-9514-b4d8d3d9a21e)

**Comment by SchwartzGandhi** [comment]
I think i know the problem for this one, this block of text needs, and interactivity attribute, can fix this tomorrow.
In the meantime, it looks like you can right click the text and paste in your browser

**Comment by SchwartzGandhi** [comment]
fixed by f4198cab6267e3327dcb24610c23b2e58995e939
